####
#### Get MongoDB up on port 27017.
####
---
- name: get basic packages for mongo
  apt: pkg={{ item }} state=present
  with_items:
    - gnupg
    - curl
# - name: get mongo key
#   shell: curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg --dearmor
- name: get mongo key
  ansible.builtin.apt_key:
    url: https://www.mongodb.org/static/pgp/server-8.0.asc
    state: present
- name: add source
  shell: echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-8.0.list
- name: apt-get update
  apt: update_cache=yes
- name: get mongo
  apt: pkg={{ item }} state=present
  with_items:
    - mongodb-org
- name: set mongodb to start on restart
  shell: systemctl enable mongod
- name: refresh daemon
  shell: systemctl daemon-reload
- name: start mongo (has localhost exception by default)
  shell: systemctl start mongod
- name: create admin
  community.mongodb.mongodb_user:
    database: admin
    name: bbopadmin
    password: "{{ mongodb_cli_password }}"
    roles: root
    login_host: 127.0.0.1
    login_port: 27017
- name: stop mongo
  shell: systemctl stop mongod
- name: get prod mongod.conf into place
  copy: src=mongod.conf dest=/etc/mongod.conf owner=root group=root mode=0644
- name: start mongo again
  shell: systemctl start mongod
