####
#### Get MongoDB up on port 27017.
####
---
- name: get basic packages for mongo
  apt: pkg={{ item }} state=present
  with_items:
    - gnupg
    - curl
- name: get mongo key
  shell: curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg --dearmor
- name: add source
  shell: echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-8.0.list
- name: apt-get update
  apt: update_cache=yes
- name: get mongo
  apt: pkg={{ item }} state=present
  with_items:
    - mongodb-org
- name: set mongodb to start on restart
  shell: systemctl enable mongod
- name: refresh daemon
  shell: systemctl daemon-reload
- name: start mongo (has localhost exception by default)
  shell: systemctl start mongod
- name: get command with secret into place
  template: "src=initial-admin-command dest=/tmp/initial-admin-command owner=mongodb group=mongodb"
- name: Run a file containing MongoDB admin commands
  community.mongodb.mongodb_shell:
    #login_user: user
    #login_password: secret
    file: "/tmp/initial-admin-command"
    #idempotent: yes
- name: stop mongo
  shell: systemctl stop mongod
- name: get prod mongod.conf into place
  copy: src=mongod.conf dest=/etc/mongod.conf owner=root group=root mode=0644
- name: start mongo again
  shell: systemctl start mongod
