####
#### Common packages across all systems.
#### This task is for 18.04.
####
---
## Get everybody up to date.
- name: apt-get update && apt-get dist-upgrade
  apt: update_cache=yes upgrade=dist
- name: install main packages
  apt: pkg={{ item }} state=present
  with_items:
    ## General repo control.
    - git
    ## General dev.
    - curl
    - jq
    - apt-utils
    - ca-certificates
    - software-properties-common
    - apt-transport-https
    - build-essential
    - mg
    ## Odds and ends utilities.
    - apt-show-versions
    - byobu
    - di
    - emacs
    - emacs-goodies-el
    - htop
    - iotop
    - less
    - make
    - mmv
    - mg
    - openssh-client
    - openssh-server
    - pandoc
    - pigz
    - s3cmd
    - sshfs
    - ntpdate
    - nscd
    - unzip
    - zip
