####
#### Install CurateGPT, setup apache proxy.
####
#### This playbook is for Ubuntu 24.04 LTS.
####
#remote_user: "{{ target_user | default('bbop') }}"
---
- hosts: "{{ target_host | default('graph-agent-production') }}"
  #remote_user: bbop
  remote_user: "{{ target_user | default('ubuntu') }}"
  become: yes
  roles:
    ## Install curategpt.
    - curategpt
