####
#### Install CurateGPT, setup apache proxy.
####
#### This playbook is for Ubuntu 24.04 LTS.
####
#remote_user: "{{ target_user | default('bbop') }}"
---
- hosts: "{{ target_host | default('graph-agent-production') }}"
  #remote_user: bbop
  remote_user: "{{ target_user | default('ubuntu') }}"
  become: yes
  roles:
    ## Install curategpt.
    - curategpt
    ## Base webserver.
    - webserver-apache
    ## Proxies back to the webservers on port.
    - role: webserver-apache-proxy
      mapping_host: alzassistant.org
      mapping_from_port: 80
      mapping_to_port: 8501
      apache_proxy_additional_rules: "    RewriteEngine On\n    RewriteCond %{HTTP:Upgrade} websocket\n    RewriteRule /(.*) ws://localhost:8501/$1 [P]\n    RewriteCond %{HTTP:Upgrade} !websocket\n    RewriteRule /(.*) http://localhost:8501/$1 [P]\n"
